name = "goldsmith"
compatibility_date = "2026-02-20"

[build]
command = "npm install && npm run build"

[site]
bucket = "./dist"

[[headers]]
for = "/*"
[headers.values]
X-Frame-Options = "DENY"
X-Content-Type-Options = "nosniff"
Referrer-Policy = "strict-origin-when-cross-origin"